name: portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/Image.jpg

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-SemiBold.ttf

    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Bold.ttf
